C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapspect1 (spect1f2pywrap, omega)
      external spect1
      real omega
      real spect1f2pywrap, spect1
      spect1f2pywrap = spect1(omega)
      end


      subroutine f2pywrapspmpar (spmparf2pywrap, i)
      external spmpar
      integer i
      real spmparf2pywrap, spmpar
      spmparf2pywrap = spmpar(i)
      end


      subroutine f2pyinitspec(setupfunc)
      external setupfunc
      real te
      real ti(10)
      real fi(10)
      real ven
      real vin(10)
      real alpha
      real dens
      real bfld
      integer nion
      integer wi(10)
      real ak
      common /spec/ te,ti,fi,ven,vin,alpha,dens,bfld,nion,wi,ak
      call setupfunc(te,ti,fi,ven,vin,alpha,dens,bfld,nion,wi,ak)
      end

      subroutine f2pyinitmode(setupfunc)
      external setupfunc
      integer imode
      common /mode/ imode
      call setupfunc(imode)
      end

      subroutine f2pyinitfitter(setupfunc)
      external setupfunc
      real tau(100)
      real rho(100)
      real sigma2(100)
      real params(10)
      integer ifit(10)
      common /fitter/ tau,rho,sigma2,params,ifit
      call setupfunc(tau,rho,sigma2,params,ifit)
      end

      subroutine f2pyinittrans(setupfunc)
      external setupfunc
      real ev(10000)
      common /trans/ ev
      call setupfunc(ev)
      end


