C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapspect1 (spect1f2pywrap, omega)
      external spect1
      real omega
      real spect1f2pywrap, spect1
      spect1f2pywrap = spect1(omega)
      end


      subroutine f2pyinitspec(setupfunc)
      external setupfunc
      real te
      real ti(10)
      real fi(10)
      real ven
      real vin(10)
      real alpha
      real dens
      real bfld
      integer nion
      integer wi(10)
      real ak
      common /spec/ te,ti,fi,ven,vin,alpha,dens,bfld,nion,wi,ak
      call setupfunc(te,ti,fi,ven,vin,alpha,dens,bfld,nion,wi,ak)
      end

      subroutine f2pyinitmode(setupfunc)
      external setupfunc
      integer imode
      common /mode/ imode
      call setupfunc(imode)
      end


