C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapcdtr1 (cdtr1f2pywrap, depth)
      external cdtr1
      real depth
      real cdtr1f2pywrap, cdtr1
      cdtr1f2pywrap = cdtr1(depth)
      end


      subroutine f2pywrapczte1 (czte1f2pywrap, zlag, tr)
      external czte1
      real zlag
      real tr
      real czte1f2pywrap, czte1
      czte1f2pywrap = czte1(zlag, tr)
      end

