C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapenorm (enormf2pywrap, n, x)
      external enorm
      integer n
      real x(n)
      real enormf2pywrap, enorm
      enormf2pywrap = enorm(n, x)
      end


      subroutine f2pywrapspmpar (spmparf2pywrap, i)
      external spmpar
      integer i
      real spmparf2pywrap, spmpar
      spmparf2pywrap = spmpar(i)
      end


      subroutine f2pywrapcdtr1 (cdtr1f2pywrap, depth)
      external cdtr1
      real depth
      real cdtr1f2pywrap, cdtr1
      cdtr1f2pywrap = cdtr1(depth)
      end


      subroutine f2pywrapczte1 (czte1f2pywrap, zlag, tr)
      external czte1
      real zlag
      real tr
      real czte1f2pywrap, czte1
      czte1f2pywrap = czte1(zlag, tr)
      end


      subroutine f2pywrapcj_ion (cj_ionf2pywrap, theta, psi)
      external cj_ion
      real theta
      real psi
      complex cj_ionf2pywrap, cj_ion
      cj_ionf2pywrap = cj_ion(theta, psi)
      end


      subroutine f2pywrapcj_electron (cj_electronf2pywrap, theta, 
     &phi, psi, alpha)
      external cj_electron
      real theta
      real phi
      real psi
      real alpha
      complex cj_electronf2pywrap, cj_electron
      cj_electronf2pywrap = cj_electron(theta, phi, psi, alpha)
      end


      subroutine f2pywrapy_ion (y_ionf2pywrap, theta, psi)
      external y_ion
      real theta
      real psi
      complex y_ionf2pywrap, y_ion
      y_ionf2pywrap = y_ion(theta, psi)
      end


      subroutine f2pywrapy_electron (y_electronf2pywrap, theta, ph
     &i, psi, alpha)
      external y_electron
      real theta
      real phi
      real psi
      real alpha
      complex y_electronf2pywrap, y_electron
      y_electronf2pywrap = y_electron(theta, phi, psi, alpha)
      end


      subroutine f2pywrapspect1 (spect1f2pywrap, omega)
      external spect1
      real omega
      real spect1f2pywrap, spect1
      spect1f2pywrap = spect1(omega)
      end


      subroutine f2pywrapatanh (atanhf2pywrap, x)
      external atanh
      real x
      real atanhf2pywrap, atanh
      atanhf2pywrap = atanh(x)
      end


      subroutine f2pywrapbvalue (bvaluef2pywrap, t, bcoef, n, k, x
     &, jderiv)
      external bvalue
      integer n
      integer k
      real x
      integer jderiv
      real t(n+k)
      real bcoef(n)
      real bvaluef2pywrap, bvalue
      bvaluef2pywrap = bvalue(t, bcoef, n, k, x, jderiv)
      end


      subroutine f2pywrapr1mach (r1machf2pywrap, i)
      external r1mach
      integer i
      real r1machf2pywrap, r1mach
      r1machf2pywrap = r1mach(i)
      end


      subroutine f2pyinitchisq(setupfunc)
      external setupfunc
      real chi2
      common /chisq/ chi2
      call setupfunc(chi2)
      end

      subroutine f2pyinitfpa(setupfunc)
      external setupfunc
      real densp(91)
      real tep(91)
      real trp(91)
      real tip(91)
      real hfp(91)
      real hefp(91)
      real altp(91)
      real r0
      real dr
      real wl
      common /fpa/ densp,tep,trp,tip,hfp,hefp,altp,r0,dr,wl
      call setupfunc(densp,tep,trp,tip,hfp,hefp,altp,r0,dr,wl)
      end

      subroutine f2pyinitdata(setupfunc)
      external setupfunc
      real plag(16,91)
      real plag_errors(16,91)
      common /data/ plag,plag_errors
      call setupfunc(plag,plag_errors)
      end

      subroutine f2pyinitsys(setupfunc)
      external setupfunc
      real sconst
      common /sys/ sconst
      call setupfunc(sconst)
      end

      subroutine f2pyiniterrs(setupfunc)
      external setupfunc
      real edensp(91)
      real etep(91)
      real etip(91)
      real ehfp(91)
      real ehefp(91)
      common /errs/ edensp,etep,etip,ehfp,ehefp
      call setupfunc(edensp,etep,etip,ehfp,ehefp)
      end

      subroutine f2pyinitmag(setupfunc)
      external setupfunc
      real bfld_prof(85)
      real alpha_prof(85)
      common /mag/ bfld_prof,alpha_prof
      call setupfunc(bfld_prof,alpha_prof)
      end

      subroutine f2pyinitmode(setupfunc)
      external setupfunc
      integer imode
      common /mode/ imode
      call setupfunc(imode)
      end

      subroutine f2pyinitutime(setupfunc)
      external setupfunc
      real uttime
      common /utime/ uttime
      call setupfunc(uttime)
      end

      subroutine f2pyinitspline(setupfunc)
      external setupfunc
      real ta(34)
      real bcoef(30,5)
      common /spline/ ta,bcoef
      call setupfunc(ta,bcoef)
      end

      subroutine f2pyinitspec(setupfunc)
      external setupfunc
      real te
      real ti(10)
      real fi(10)
      real ven
      real vin(10)
      real alpha
      real dens
      real bfld
      integer nion
      integer wi(10)
      real ak
      common /spec/ te,ti,fi,ven,vin,alpha,dens,bfld,nion,wi,ak
      call setupfunc(te,ti,fi,ven,vin,alpha,dens,bfld,nion,wi,ak)
      end

      subroutine f2pyinitfitter(setupfunc)
      external setupfunc
      real tau(100)
      real rho(100)
      real sigma2(100)
      real params(10)
      integer ifit(10)
      common /fitter/ tau,rho,sigma2,params,ifit
      call setupfunc(tau,rho,sigma2,params,ifit)
      end

      subroutine f2pyinittrans(setupfunc)
      external setupfunc
      real ev(10000)
      common /trans/ ev
      call setupfunc(ev)
      end

      subroutine f2pyinitd8mach(setupfunc)
      external setupfunc
      integer cray1
      common /d8mach/ cray1
      call setupfunc(cray1)
      end


