/* File: mkfact_short_2020_2module.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Mon Nov 24 21:35:12 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *mkfact_short_2020_2_error;
static PyObject *mkfact_short_2020_2_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(mkfact_short_2020_2_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = mkfact_short_2020_2_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
    double d=0.0;
    if (double_from_pyobj(&d,obj,errmess)) {
        *v = (float)d;
        return 1;
    }
    return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = mkfact_short_2020_2_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
    PyArrayObject *arr = NULL;
    PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
    if (obj == Py_None) {
        if (*len == -1)
            *len = strlen(inistr); /* Will this cause problems? */
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,inistr,*len+1);
        return 1;
    }
    if (PyArray_Check(obj)) {
        if ((arr = (PyArrayObject *)obj) == NULL)
            goto capi_fail;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
            goto capi_fail;
        }
        if (*len == -1)
            *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
        return 1;
    }
    if (PyString_Check(obj)) {
        tmp = obj;
        Py_INCREF(tmp);
    }
    else if (PyUnicode_Check(obj)) {
        tmp = PyUnicode_AsASCIIString(obj);
    }
    else {
        PyObject *tmp2;
        tmp2 = PyObject_Str(obj);
        if (tmp2) {
            tmp = PyUnicode_AsASCIIString(tmp2);
            Py_DECREF(tmp2);
        }
        else {
            tmp = NULL;
        }
    }
    if (tmp == NULL) goto capi_fail;
    if (*len == -1)
        *len = PyString_GET_SIZE(tmp);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
    Py_DECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = mkfact_short_2020_2_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(mkfact,MKFACT)(float*,float*,float*,float*,float*,int*);
extern void F_FUNC(geobfield,GEOBFIELD)(float*,float*,float*,float*,float*,float*,float*,float*);
extern void F_FUNC(convrt,CONVRT)(int*,float*,float*,float*,float*);
extern void F_FUNC(getshc2,GETSHC2)(int*,string,int*,float*,float*,int*,size_t);
extern void F_FUNC(interpshc,INTERPSHC)(float*,float*,int*,float*,float*,int*,float*,int*,float*);
extern void F_FUNC(extrapshc,EXTRAPSHC)(float*,float*,int*,float*,int*,float*,int*,float*);
extern void F_FUNC(shval3,SHVAL3)(int*,float*,float*,float*,float*,float*,float*,int*,float*,int*,float*,float*,float*,float*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** mkfact ***********************************/
static char doc_f2py_rout_mkfact_short_2020_2_mkfact[] = "\
mkfact(tm,h,bfm,thb,bki,[nhts])\n\nWrapper for ``mkfact``.\
\n\nParameters\n----------\n"
"tm : input float\n"
"h : input rank-1 array('f') with bounds (nhts)\n"
"bfm : in/output rank-1 array('f') with bounds (nhts)\n"
"thb : in/output rank-1 array('f') with bounds (nhts)\n"
"bki : in/output rank-1 array('f') with bounds (nhts)\n"
"\nOther Parameters\n----------------\n"
"nhts : input int, optional\n    Default: len(h)";
/* extern void F_FUNC(mkfact,MKFACT)(float*,float*,float*,float*,float*,int*); */
static PyObject *f2py_rout_mkfact_short_2020_2_mkfact(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,float*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float tm = 0;
  PyObject *tm_capi = Py_None;
  float *h = NULL;
  npy_intp h_Dims[1] = {-1};
  const int h_Rank = 1;
  PyArrayObject *capi_h_tmp = NULL;
  int capi_h_intent = 0;
  PyObject *h_capi = Py_None;
  float *bfm = NULL;
  npy_intp bfm_Dims[1] = {-1};
  const int bfm_Rank = 1;
  PyArrayObject *capi_bfm_tmp = NULL;
  int capi_bfm_intent = 0;
  PyObject *bfm_capi = Py_None;
  float *thb = NULL;
  npy_intp thb_Dims[1] = {-1};
  const int thb_Rank = 1;
  PyArrayObject *capi_thb_tmp = NULL;
  int capi_thb_intent = 0;
  PyObject *thb_capi = Py_None;
  float *bki = NULL;
  npy_intp bki_Dims[1] = {-1};
  const int bki_Rank = 1;
  PyArrayObject *capi_bki_tmp = NULL;
  int capi_bki_intent = 0;
  PyObject *bki_capi = Py_None;
  int nhts = 0;
  PyObject *nhts_capi = Py_None;
  static char *capi_kwlist[] = {"tm","h","bfm","thb","bki","nhts",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|O:mkfact_short_2020_2.mkfact",\
    capi_kwlist,&tm_capi,&h_capi,&bfm_capi,&thb_capi,&bki_capi,&nhts_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable tm */
    f2py_success = float_from_pyobj(&tm,tm_capi,"mkfact_short_2020_2.mkfact() 1st argument (tm) can't be converted to float");
  if (f2py_success) {
  /* Processing variable h */
  ;
  capi_h_intent |= F2PY_INTENT_IN;
  capi_h_tmp = array_from_pyobj(NPY_FLOAT,h_Dims,h_Rank,capi_h_intent,h_capi);
  if (capi_h_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : mkfact_short_2020_2_error,"failed in converting 2nd argument `h' of mkfact_short_2020_2.mkfact to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    h = (float *)(PyArray_DATA(capi_h_tmp));

  /* Processing variable nhts */
  if (nhts_capi == Py_None) nhts = len(h); else
    f2py_success = int_from_pyobj(&nhts,nhts_capi,"mkfact_short_2020_2.mkfact() 1st keyword (nhts) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(h)>=nhts,"len(h)>=nhts","1st keyword nhts","mkfact:nhts=%d",nhts) {
  /* Processing variable bfm */
  bfm_Dims[0]=nhts;
  capi_bfm_intent |= F2PY_INTENT_INOUT;
  capi_bfm_tmp = array_from_pyobj(NPY_FLOAT,bfm_Dims,bfm_Rank,capi_bfm_intent,bfm_capi);
  if (capi_bfm_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : mkfact_short_2020_2_error,"failed in converting 3rd argument `bfm' of mkfact_short_2020_2.mkfact to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    bfm = (float *)(PyArray_DATA(capi_bfm_tmp));

  /* Processing variable thb */
  thb_Dims[0]=nhts;
  capi_thb_intent |= F2PY_INTENT_INOUT;
  capi_thb_tmp = array_from_pyobj(NPY_FLOAT,thb_Dims,thb_Rank,capi_thb_intent,thb_capi);
  if (capi_thb_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : mkfact_short_2020_2_error,"failed in converting 4th argument `thb' of mkfact_short_2020_2.mkfact to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    thb = (float *)(PyArray_DATA(capi_thb_tmp));

  /* Processing variable bki */
  bki_Dims[0]=nhts;
  capi_bki_intent |= F2PY_INTENT_INOUT;
  capi_bki_tmp = array_from_pyobj(NPY_FLOAT,bki_Dims,bki_Rank,capi_bki_intent,bki_capi);
  if (capi_bki_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : mkfact_short_2020_2_error,"failed in converting 5th argument `bki' of mkfact_short_2020_2.mkfact to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    bki = (float *)(PyArray_DATA(capi_bki_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&tm,h,bfm,thb,bki,&nhts);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_bki_tmp!=bki_capi) {
    Py_XDECREF(capi_bki_tmp); }
  }  /*if (capi_bki_tmp == NULL) ... else of bki*/
  /* End of cleaning variable bki */
  if((PyObject *)capi_thb_tmp!=thb_capi) {
    Py_XDECREF(capi_thb_tmp); }
  }  /*if (capi_thb_tmp == NULL) ... else of thb*/
  /* End of cleaning variable thb */
  if((PyObject *)capi_bfm_tmp!=bfm_capi) {
    Py_XDECREF(capi_bfm_tmp); }
  }  /*if (capi_bfm_tmp == NULL) ... else of bfm*/
  /* End of cleaning variable bfm */
  } /*CHECKSCALAR(len(h)>=nhts)*/
  } /*if (f2py_success) of nhts*/
  /* End of cleaning variable nhts */
  if((PyObject *)capi_h_tmp!=h_capi) {
    Py_XDECREF(capi_h_tmp); }
  }  /*if (capi_h_tmp == NULL) ... else of h*/
  /* End of cleaning variable h */
  } /*if (f2py_success) of tm*/
  /* End of cleaning variable tm */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of mkfact *******************************/

/********************************* geobfield *********************************/
static char doc_f2py_rout_mkfact_short_2020_2_geobfield[] = "\
geobfield(tm,r,theta,phi,br,bt,bp,b)\n\nWrapper for ``geobfield``.\
\n\nParameters\n----------\n"
"tm : input float\n"
"r : input float\n"
"theta : input float\n"
"phi : input float\n"
"br : input float\n"
"bt : input float\n"
"bp : input float\n"
"b : input float";
/* extern void F_FUNC(geobfield,GEOBFIELD)(float*,float*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_mkfact_short_2020_2_geobfield(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float tm = 0;
  PyObject *tm_capi = Py_None;
  float r = 0;
  PyObject *r_capi = Py_None;
  float theta = 0;
  PyObject *theta_capi = Py_None;
  float phi = 0;
  PyObject *phi_capi = Py_None;
  float br = 0;
  PyObject *br_capi = Py_None;
  float bt = 0;
  PyObject *bt_capi = Py_None;
  float bp = 0;
  PyObject *bp_capi = Py_None;
  float b = 0;
  PyObject *b_capi = Py_None;
  static char *capi_kwlist[] = {"tm","r","theta","phi","br","bt","bp","b",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO|:mkfact_short_2020_2.geobfield",\
    capi_kwlist,&tm_capi,&r_capi,&theta_capi,&phi_capi,&br_capi,&bt_capi,&bp_capi,&b_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable tm */
    f2py_success = float_from_pyobj(&tm,tm_capi,"mkfact_short_2020_2.geobfield() 1st argument (tm) can't be converted to float");
  if (f2py_success) {
  /* Processing variable r */
    f2py_success = float_from_pyobj(&r,r_capi,"mkfact_short_2020_2.geobfield() 2nd argument (r) can't be converted to float");
  if (f2py_success) {
  /* Processing variable theta */
    f2py_success = float_from_pyobj(&theta,theta_capi,"mkfact_short_2020_2.geobfield() 3rd argument (theta) can't be converted to float");
  if (f2py_success) {
  /* Processing variable phi */
    f2py_success = float_from_pyobj(&phi,phi_capi,"mkfact_short_2020_2.geobfield() 4th argument (phi) can't be converted to float");
  if (f2py_success) {
  /* Processing variable br */
    f2py_success = float_from_pyobj(&br,br_capi,"mkfact_short_2020_2.geobfield() 5th argument (br) can't be converted to float");
  if (f2py_success) {
  /* Processing variable bt */
    f2py_success = float_from_pyobj(&bt,bt_capi,"mkfact_short_2020_2.geobfield() 6th argument (bt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable bp */
    f2py_success = float_from_pyobj(&bp,bp_capi,"mkfact_short_2020_2.geobfield() 7th argument (bp) can't be converted to float");
  if (f2py_success) {
  /* Processing variable b */
    f2py_success = float_from_pyobj(&b,b_capi,"mkfact_short_2020_2.geobfield() 8th argument (b) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&tm,&r,&theta,&phi,&br,&bt,&bp,&b);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of b*/
  /* End of cleaning variable b */
  } /*if (f2py_success) of bp*/
  /* End of cleaning variable bp */
  } /*if (f2py_success) of bt*/
  /* End of cleaning variable bt */
  } /*if (f2py_success) of br*/
  /* End of cleaning variable br */
  } /*if (f2py_success) of phi*/
  /* End of cleaning variable phi */
  } /*if (f2py_success) of theta*/
  /* End of cleaning variable theta */
  } /*if (f2py_success) of r*/
  /* End of cleaning variable r */
  } /*if (f2py_success) of tm*/
  /* End of cleaning variable tm */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of geobfield ******************************/

/*********************************** convrt ***********************************/
static char doc_f2py_rout_mkfact_short_2020_2_convrt[] = "\
convrt(i,gdlat,gdalt,gclat,rkm)\n\nWrapper for ``convrt``.\
\n\nParameters\n----------\n"
"i : input int\n"
"gdlat : input float\n"
"gdalt : input float\n"
"gclat : input float\n"
"rkm : input float";
/* extern void F_FUNC(convrt,CONVRT)(int*,float*,float*,float*,float*); */
static PyObject *f2py_rout_mkfact_short_2020_2_convrt(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int i = 0;
  PyObject *i_capi = Py_None;
  float gdlat = 0;
  PyObject *gdlat_capi = Py_None;
  float gdalt = 0;
  PyObject *gdalt_capi = Py_None;
  float gclat = 0;
  PyObject *gclat_capi = Py_None;
  float rkm = 0;
  PyObject *rkm_capi = Py_None;
  static char *capi_kwlist[] = {"i","gdlat","gdalt","gclat","rkm",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|:mkfact_short_2020_2.convrt",\
    capi_kwlist,&i_capi,&gdlat_capi,&gdalt_capi,&gclat_capi,&rkm_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable i */
    f2py_success = int_from_pyobj(&i,i_capi,"mkfact_short_2020_2.convrt() 1st argument (i) can't be converted to int");
  if (f2py_success) {
  /* Processing variable gdlat */
    f2py_success = float_from_pyobj(&gdlat,gdlat_capi,"mkfact_short_2020_2.convrt() 2nd argument (gdlat) can't be converted to float");
  if (f2py_success) {
  /* Processing variable gdalt */
    f2py_success = float_from_pyobj(&gdalt,gdalt_capi,"mkfact_short_2020_2.convrt() 3rd argument (gdalt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable gclat */
    f2py_success = float_from_pyobj(&gclat,gclat_capi,"mkfact_short_2020_2.convrt() 4th argument (gclat) can't be converted to float");
  if (f2py_success) {
  /* Processing variable rkm */
    f2py_success = float_from_pyobj(&rkm,rkm_capi,"mkfact_short_2020_2.convrt() 5th argument (rkm) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&i,&gdlat,&gdalt,&gclat,&rkm);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of rkm*/
  /* End of cleaning variable rkm */
  } /*if (f2py_success) of gclat*/
  /* End of cleaning variable gclat */
  } /*if (f2py_success) of gdalt*/
  /* End of cleaning variable gdalt */
  } /*if (f2py_success) of gdlat*/
  /* End of cleaning variable gdlat */
  } /*if (f2py_success) of i*/
  /* End of cleaning variable i */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of convrt *******************************/

/********************************** getshc2 **********************************/
static char doc_f2py_rout_mkfact_short_2020_2_getshc2[] = "\
getshc2(iu,fspec,nmax,erad,gh,ier)\n\nWrapper for ``getshc2``.\
\n\nParameters\n----------\n"
"iu : input int\n"
"fspec : input string(len=-1)\n"
"nmax : input int\n"
"erad : input float\n"
"gh : input rank-1 array('f') with bounds (*)\n"
"ier : input int";
/* extern void F_FUNC(getshc2,GETSHC2)(int*,string,int*,float*,float*,int*,size_t); */
static PyObject *f2py_rout_mkfact_short_2020_2_getshc2(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,int*,float*,float*,int*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int iu = 0;
  PyObject *iu_capi = Py_None;
  string fspec = NULL;
  int slen(fspec);
  PyObject *fspec_capi = Py_None;
  int nmax = 0;
  PyObject *nmax_capi = Py_None;
  float erad = 0;
  PyObject *erad_capi = Py_None;
  float *gh = NULL;
  npy_intp gh_Dims[1] = {-1};
  const int gh_Rank = 1;
  PyArrayObject *capi_gh_tmp = NULL;
  int capi_gh_intent = 0;
  PyObject *gh_capi = Py_None;
  int ier = 0;
  PyObject *ier_capi = Py_None;
  static char *capi_kwlist[] = {"iu","fspec","nmax","erad","gh","ier",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|:mkfact_short_2020_2.getshc2",\
    capi_kwlist,&iu_capi,&fspec_capi,&nmax_capi,&erad_capi,&gh_capi,&ier_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable iu */
    f2py_success = int_from_pyobj(&iu,iu_capi,"mkfact_short_2020_2.getshc2() 1st argument (iu) can't be converted to int");
  if (f2py_success) {
  /* Processing variable fspec */
  slen(fspec) = -1;
  f2py_success = string_from_pyobj(&fspec,&slen(fspec),"",fspec_capi,"string_from_pyobj failed in converting 2nd argument `fspec' of mkfact_short_2020_2.getshc2 to C string");
  if (f2py_success) {
  /* Processing variable nmax */
    f2py_success = int_from_pyobj(&nmax,nmax_capi,"mkfact_short_2020_2.getshc2() 3rd argument (nmax) can't be converted to int");
  if (f2py_success) {
  /* Processing variable erad */
    f2py_success = float_from_pyobj(&erad,erad_capi,"mkfact_short_2020_2.getshc2() 4th argument (erad) can't be converted to float");
  if (f2py_success) {
  /* Processing variable gh */
  ;
  capi_gh_intent |= F2PY_INTENT_IN;
  capi_gh_tmp = array_from_pyobj(NPY_FLOAT,gh_Dims,gh_Rank,capi_gh_intent,gh_capi);
  if (capi_gh_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : mkfact_short_2020_2_error,"failed in converting 5th argument `gh' of mkfact_short_2020_2.getshc2 to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    gh = (float *)(PyArray_DATA(capi_gh_tmp));

  /* Processing variable ier */
    f2py_success = int_from_pyobj(&ier,ier_capi,"mkfact_short_2020_2.getshc2() 6th argument (ier) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&iu,fspec,&nmax,&erad,gh,&ier,slen(fspec));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of ier*/
  /* End of cleaning variable ier */
  if((PyObject *)capi_gh_tmp!=gh_capi) {
    Py_XDECREF(capi_gh_tmp); }
  }  /*if (capi_gh_tmp == NULL) ... else of gh*/
  /* End of cleaning variable gh */
  } /*if (f2py_success) of erad*/
  /* End of cleaning variable erad */
  } /*if (f2py_success) of nmax*/
  /* End of cleaning variable nmax */
    STRINGFREE(fspec);
  }  /*if (f2py_success) of fspec*/
  /* End of cleaning variable fspec */
  } /*if (f2py_success) of iu*/
  /* End of cleaning variable iu */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of getshc2 *******************************/

/********************************* interpshc *********************************/
static char doc_f2py_rout_mkfact_short_2020_2_interpshc[] = "\
interpshc(date,dte1,nmax1,gh1,dte2,nmax2,gh2,nmax,gh)\n\nWrapper for ``interpshc``.\
\n\nParameters\n----------\n"
"date : input float\n"
"dte1 : input float\n"
"nmax1 : input int\n"
"gh1 : input rank-1 array('f') with bounds (*)\n"
"dte2 : input float\n"
"nmax2 : input int\n"
"gh2 : input rank-1 array('f') with bounds (*)\n"
"nmax : input int\n"
"gh : input rank-1 array('f') with bounds (*)";
/* extern void F_FUNC(interpshc,INTERPSHC)(float*,float*,int*,float*,float*,int*,float*,int*,float*); */
static PyObject *f2py_rout_mkfact_short_2020_2_interpshc(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,int*,float*,float*,int*,float*,int*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float date = 0;
  PyObject *date_capi = Py_None;
  float dte1 = 0;
  PyObject *dte1_capi = Py_None;
  int nmax1 = 0;
  PyObject *nmax1_capi = Py_None;
  float *gh1 = NULL;
  npy_intp gh1_Dims[1] = {-1};
  const int gh1_Rank = 1;
  PyArrayObject *capi_gh1_tmp = NULL;
  int capi_gh1_intent = 0;
  PyObject *gh1_capi = Py_None;
  float dte2 = 0;
  PyObject *dte2_capi = Py_None;
  int nmax2 = 0;
  PyObject *nmax2_capi = Py_None;
  float *gh2 = NULL;
  npy_intp gh2_Dims[1] = {-1};
  const int gh2_Rank = 1;
  PyArrayObject *capi_gh2_tmp = NULL;
  int capi_gh2_intent = 0;
  PyObject *gh2_capi = Py_None;
  int nmax = 0;
  PyObject *nmax_capi = Py_None;
  float *gh = NULL;
  npy_intp gh_Dims[1] = {-1};
  const int gh_Rank = 1;
  PyArrayObject *capi_gh_tmp = NULL;
  int capi_gh_intent = 0;
  PyObject *gh_capi = Py_None;
  static char *capi_kwlist[] = {"date","dte1","nmax1","gh1","dte2","nmax2","gh2","nmax","gh",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO|:mkfact_short_2020_2.interpshc",\
    capi_kwlist,&date_capi,&dte1_capi,&nmax1_capi,&gh1_capi,&dte2_capi,&nmax2_capi,&gh2_capi,&nmax_capi,&gh_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable date */
    f2py_success = float_from_pyobj(&date,date_capi,"mkfact_short_2020_2.interpshc() 1st argument (date) can't be converted to float");
  if (f2py_success) {
  /* Processing variable dte1 */
    f2py_success = float_from_pyobj(&dte1,dte1_capi,"mkfact_short_2020_2.interpshc() 2nd argument (dte1) can't be converted to float");
  if (f2py_success) {
  /* Processing variable nmax1 */
    f2py_success = int_from_pyobj(&nmax1,nmax1_capi,"mkfact_short_2020_2.interpshc() 3rd argument (nmax1) can't be converted to int");
  if (f2py_success) {
  /* Processing variable gh1 */
  ;
  capi_gh1_intent |= F2PY_INTENT_IN;
  capi_gh1_tmp = array_from_pyobj(NPY_FLOAT,gh1_Dims,gh1_Rank,capi_gh1_intent,gh1_capi);
  if (capi_gh1_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : mkfact_short_2020_2_error,"failed in converting 4th argument `gh1' of mkfact_short_2020_2.interpshc to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    gh1 = (float *)(PyArray_DATA(capi_gh1_tmp));

  /* Processing variable dte2 */
    f2py_success = float_from_pyobj(&dte2,dte2_capi,"mkfact_short_2020_2.interpshc() 5th argument (dte2) can't be converted to float");
  if (f2py_success) {
  /* Processing variable nmax2 */
    f2py_success = int_from_pyobj(&nmax2,nmax2_capi,"mkfact_short_2020_2.interpshc() 6th argument (nmax2) can't be converted to int");
  if (f2py_success) {
  /* Processing variable gh2 */
  ;
  capi_gh2_intent |= F2PY_INTENT_IN;
  capi_gh2_tmp = array_from_pyobj(NPY_FLOAT,gh2_Dims,gh2_Rank,capi_gh2_intent,gh2_capi);
  if (capi_gh2_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : mkfact_short_2020_2_error,"failed in converting 7th argument `gh2' of mkfact_short_2020_2.interpshc to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    gh2 = (float *)(PyArray_DATA(capi_gh2_tmp));

  /* Processing variable nmax */
    f2py_success = int_from_pyobj(&nmax,nmax_capi,"mkfact_short_2020_2.interpshc() 8th argument (nmax) can't be converted to int");
  if (f2py_success) {
  /* Processing variable gh */
  ;
  capi_gh_intent |= F2PY_INTENT_IN;
  capi_gh_tmp = array_from_pyobj(NPY_FLOAT,gh_Dims,gh_Rank,capi_gh_intent,gh_capi);
  if (capi_gh_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : mkfact_short_2020_2_error,"failed in converting 9th argument `gh' of mkfact_short_2020_2.interpshc to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    gh = (float *)(PyArray_DATA(capi_gh_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&date,&dte1,&nmax1,gh1,&dte2,&nmax2,gh2,&nmax,gh);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_gh_tmp!=gh_capi) {
    Py_XDECREF(capi_gh_tmp); }
  }  /*if (capi_gh_tmp == NULL) ... else of gh*/
  /* End of cleaning variable gh */
  } /*if (f2py_success) of nmax*/
  /* End of cleaning variable nmax */
  if((PyObject *)capi_gh2_tmp!=gh2_capi) {
    Py_XDECREF(capi_gh2_tmp); }
  }  /*if (capi_gh2_tmp == NULL) ... else of gh2*/
  /* End of cleaning variable gh2 */
  } /*if (f2py_success) of nmax2*/
  /* End of cleaning variable nmax2 */
  } /*if (f2py_success) of dte2*/
  /* End of cleaning variable dte2 */
  if((PyObject *)capi_gh1_tmp!=gh1_capi) {
    Py_XDECREF(capi_gh1_tmp); }
  }  /*if (capi_gh1_tmp == NULL) ... else of gh1*/
  /* End of cleaning variable gh1 */
  } /*if (f2py_success) of nmax1*/
  /* End of cleaning variable nmax1 */
  } /*if (f2py_success) of dte1*/
  /* End of cleaning variable dte1 */
  } /*if (f2py_success) of date*/
  /* End of cleaning variable date */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of interpshc ******************************/

/********************************* extrapshc *********************************/
static char doc_f2py_rout_mkfact_short_2020_2_extrapshc[] = "\
extrapshc(date,dte1,nmax1,gh1,nmax2,gh2,nmax,gh)\n\nWrapper for ``extrapshc``.\
\n\nParameters\n----------\n"
"date : input float\n"
"dte1 : input float\n"
"nmax1 : input int\n"
"gh1 : input rank-1 array('f') with bounds (*)\n"
"nmax2 : input int\n"
"gh2 : input rank-1 array('f') with bounds (*)\n"
"nmax : input int\n"
"gh : input rank-1 array('f') with bounds (*)";
/* extern void F_FUNC(extrapshc,EXTRAPSHC)(float*,float*,int*,float*,int*,float*,int*,float*); */
static PyObject *f2py_rout_mkfact_short_2020_2_extrapshc(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,int*,float*,int*,float*,int*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float date = 0;
  PyObject *date_capi = Py_None;
  float dte1 = 0;
  PyObject *dte1_capi = Py_None;
  int nmax1 = 0;
  PyObject *nmax1_capi = Py_None;
  float *gh1 = NULL;
  npy_intp gh1_Dims[1] = {-1};
  const int gh1_Rank = 1;
  PyArrayObject *capi_gh1_tmp = NULL;
  int capi_gh1_intent = 0;
  PyObject *gh1_capi = Py_None;
  int nmax2 = 0;
  PyObject *nmax2_capi = Py_None;
  float *gh2 = NULL;
  npy_intp gh2_Dims[1] = {-1};
  const int gh2_Rank = 1;
  PyArrayObject *capi_gh2_tmp = NULL;
  int capi_gh2_intent = 0;
  PyObject *gh2_capi = Py_None;
  int nmax = 0;
  PyObject *nmax_capi = Py_None;
  float *gh = NULL;
  npy_intp gh_Dims[1] = {-1};
  const int gh_Rank = 1;
  PyArrayObject *capi_gh_tmp = NULL;
  int capi_gh_intent = 0;
  PyObject *gh_capi = Py_None;
  static char *capi_kwlist[] = {"date","dte1","nmax1","gh1","nmax2","gh2","nmax","gh",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO|:mkfact_short_2020_2.extrapshc",\
    capi_kwlist,&date_capi,&dte1_capi,&nmax1_capi,&gh1_capi,&nmax2_capi,&gh2_capi,&nmax_capi,&gh_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable date */
    f2py_success = float_from_pyobj(&date,date_capi,"mkfact_short_2020_2.extrapshc() 1st argument (date) can't be converted to float");
  if (f2py_success) {
  /* Processing variable dte1 */
    f2py_success = float_from_pyobj(&dte1,dte1_capi,"mkfact_short_2020_2.extrapshc() 2nd argument (dte1) can't be converted to float");
  if (f2py_success) {
  /* Processing variable nmax1 */
    f2py_success = int_from_pyobj(&nmax1,nmax1_capi,"mkfact_short_2020_2.extrapshc() 3rd argument (nmax1) can't be converted to int");
  if (f2py_success) {
  /* Processing variable gh1 */
  ;
  capi_gh1_intent |= F2PY_INTENT_IN;
  capi_gh1_tmp = array_from_pyobj(NPY_FLOAT,gh1_Dims,gh1_Rank,capi_gh1_intent,gh1_capi);
  if (capi_gh1_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : mkfact_short_2020_2_error,"failed in converting 4th argument `gh1' of mkfact_short_2020_2.extrapshc to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    gh1 = (float *)(PyArray_DATA(capi_gh1_tmp));

  /* Processing variable nmax2 */
    f2py_success = int_from_pyobj(&nmax2,nmax2_capi,"mkfact_short_2020_2.extrapshc() 5th argument (nmax2) can't be converted to int");
  if (f2py_success) {
  /* Processing variable gh2 */
  ;
  capi_gh2_intent |= F2PY_INTENT_IN;
  capi_gh2_tmp = array_from_pyobj(NPY_FLOAT,gh2_Dims,gh2_Rank,capi_gh2_intent,gh2_capi);
  if (capi_gh2_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : mkfact_short_2020_2_error,"failed in converting 6th argument `gh2' of mkfact_short_2020_2.extrapshc to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    gh2 = (float *)(PyArray_DATA(capi_gh2_tmp));

  /* Processing variable nmax */
    f2py_success = int_from_pyobj(&nmax,nmax_capi,"mkfact_short_2020_2.extrapshc() 7th argument (nmax) can't be converted to int");
  if (f2py_success) {
  /* Processing variable gh */
  ;
  capi_gh_intent |= F2PY_INTENT_IN;
  capi_gh_tmp = array_from_pyobj(NPY_FLOAT,gh_Dims,gh_Rank,capi_gh_intent,gh_capi);
  if (capi_gh_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : mkfact_short_2020_2_error,"failed in converting 8th argument `gh' of mkfact_short_2020_2.extrapshc to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    gh = (float *)(PyArray_DATA(capi_gh_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&date,&dte1,&nmax1,gh1,&nmax2,gh2,&nmax,gh);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_gh_tmp!=gh_capi) {
    Py_XDECREF(capi_gh_tmp); }
  }  /*if (capi_gh_tmp == NULL) ... else of gh*/
  /* End of cleaning variable gh */
  } /*if (f2py_success) of nmax*/
  /* End of cleaning variable nmax */
  if((PyObject *)capi_gh2_tmp!=gh2_capi) {
    Py_XDECREF(capi_gh2_tmp); }
  }  /*if (capi_gh2_tmp == NULL) ... else of gh2*/
  /* End of cleaning variable gh2 */
  } /*if (f2py_success) of nmax2*/
  /* End of cleaning variable nmax2 */
  if((PyObject *)capi_gh1_tmp!=gh1_capi) {
    Py_XDECREF(capi_gh1_tmp); }
  }  /*if (capi_gh1_tmp == NULL) ... else of gh1*/
  /* End of cleaning variable gh1 */
  } /*if (f2py_success) of nmax1*/
  /* End of cleaning variable nmax1 */
  } /*if (f2py_success) of dte1*/
  /* End of cleaning variable dte1 */
  } /*if (f2py_success) of date*/
  /* End of cleaning variable date */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of extrapshc ******************************/

/*********************************** shval3 ***********************************/
static char doc_f2py_rout_mkfact_short_2020_2_shval3[] = "\
shval3(igdgc,flat,flon,elev,erad,a2,b2,nmax,gh,iext,ext,x,y,z)\n\nWrapper for ``shval3``.\
\n\nParameters\n----------\n"
"igdgc : input int\n"
"flat : input float\n"
"flon : input float\n"
"elev : input float\n"
"erad : input float\n"
"a2 : input float\n"
"b2 : input float\n"
"nmax : input int\n"
"gh : input rank-1 array('f') with bounds (224)\n"
"iext : input int\n"
"ext : input rank-1 array('f') with bounds (3)\n"
"x : input float\n"
"y : input float\n"
"z : input float";
/* extern void F_FUNC(shval3,SHVAL3)(int*,float*,float*,float*,float*,float*,float*,int*,float*,int*,float*,float*,float*,float*); */
static PyObject *f2py_rout_mkfact_short_2020_2_shval3(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*,float*,float*,int*,float*,int*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int igdgc = 0;
  PyObject *igdgc_capi = Py_None;
  float flat = 0;
  PyObject *flat_capi = Py_None;
  float flon = 0;
  PyObject *flon_capi = Py_None;
  float elev = 0;
  PyObject *elev_capi = Py_None;
  float erad = 0;
  PyObject *erad_capi = Py_None;
  float a2 = 0;
  PyObject *a2_capi = Py_None;
  float b2 = 0;
  PyObject *b2_capi = Py_None;
  int nmax = 0;
  PyObject *nmax_capi = Py_None;
  float *gh = NULL;
  npy_intp gh_Dims[1] = {-1};
  const int gh_Rank = 1;
  PyArrayObject *capi_gh_tmp = NULL;
  int capi_gh_intent = 0;
  PyObject *gh_capi = Py_None;
  int iext = 0;
  PyObject *iext_capi = Py_None;
  float *ext = NULL;
  npy_intp ext_Dims[1] = {-1};
  const int ext_Rank = 1;
  PyArrayObject *capi_ext_tmp = NULL;
  int capi_ext_intent = 0;
  PyObject *ext_capi = Py_None;
  float x = 0;
  PyObject *x_capi = Py_None;
  float y = 0;
  PyObject *y_capi = Py_None;
  float z = 0;
  PyObject *z_capi = Py_None;
  static char *capi_kwlist[] = {"igdgc","flat","flon","elev","erad","a2","b2","nmax","gh","iext","ext","x","y","z",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOO|:mkfact_short_2020_2.shval3",\
    capi_kwlist,&igdgc_capi,&flat_capi,&flon_capi,&elev_capi,&erad_capi,&a2_capi,&b2_capi,&nmax_capi,&gh_capi,&iext_capi,&ext_capi,&x_capi,&y_capi,&z_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable igdgc */
    f2py_success = int_from_pyobj(&igdgc,igdgc_capi,"mkfact_short_2020_2.shval3() 1st argument (igdgc) can't be converted to int");
  if (f2py_success) {
  /* Processing variable flat */
    f2py_success = float_from_pyobj(&flat,flat_capi,"mkfact_short_2020_2.shval3() 2nd argument (flat) can't be converted to float");
  if (f2py_success) {
  /* Processing variable flon */
    f2py_success = float_from_pyobj(&flon,flon_capi,"mkfact_short_2020_2.shval3() 3rd argument (flon) can't be converted to float");
  if (f2py_success) {
  /* Processing variable elev */
    f2py_success = float_from_pyobj(&elev,elev_capi,"mkfact_short_2020_2.shval3() 4th argument (elev) can't be converted to float");
  if (f2py_success) {
  /* Processing variable erad */
    f2py_success = float_from_pyobj(&erad,erad_capi,"mkfact_short_2020_2.shval3() 5th argument (erad) can't be converted to float");
  if (f2py_success) {
  /* Processing variable a2 */
    f2py_success = float_from_pyobj(&a2,a2_capi,"mkfact_short_2020_2.shval3() 6th argument (a2) can't be converted to float");
  if (f2py_success) {
  /* Processing variable b2 */
    f2py_success = float_from_pyobj(&b2,b2_capi,"mkfact_short_2020_2.shval3() 7th argument (b2) can't be converted to float");
  if (f2py_success) {
  /* Processing variable nmax */
    f2py_success = int_from_pyobj(&nmax,nmax_capi,"mkfact_short_2020_2.shval3() 8th argument (nmax) can't be converted to int");
  if (f2py_success) {
  /* Processing variable gh */
  gh_Dims[0]=224;
  capi_gh_intent |= F2PY_INTENT_IN;
  capi_gh_tmp = array_from_pyobj(NPY_FLOAT,gh_Dims,gh_Rank,capi_gh_intent,gh_capi);
  if (capi_gh_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : mkfact_short_2020_2_error,"failed in converting 9th argument `gh' of mkfact_short_2020_2.shval3 to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    gh = (float *)(PyArray_DATA(capi_gh_tmp));

  /* Processing variable iext */
    f2py_success = int_from_pyobj(&iext,iext_capi,"mkfact_short_2020_2.shval3() 10th argument (iext) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ext */
  ext_Dims[0]=3;
  capi_ext_intent |= F2PY_INTENT_IN;
  capi_ext_tmp = array_from_pyobj(NPY_FLOAT,ext_Dims,ext_Rank,capi_ext_intent,ext_capi);
  if (capi_ext_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : mkfact_short_2020_2_error,"failed in converting 11st argument `ext' of mkfact_short_2020_2.shval3 to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    ext = (float *)(PyArray_DATA(capi_ext_tmp));

  /* Processing variable x */
    f2py_success = float_from_pyobj(&x,x_capi,"mkfact_short_2020_2.shval3() 12nd argument (x) can't be converted to float");
  if (f2py_success) {
  /* Processing variable y */
    f2py_success = float_from_pyobj(&y,y_capi,"mkfact_short_2020_2.shval3() 13rd argument (y) can't be converted to float");
  if (f2py_success) {
  /* Processing variable z */
    f2py_success = float_from_pyobj(&z,z_capi,"mkfact_short_2020_2.shval3() 14th argument (z) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&igdgc,&flat,&flon,&elev,&erad,&a2,&b2,&nmax,gh,&iext,ext,&x,&y,&z);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of z*/
  /* End of cleaning variable z */
  } /*if (f2py_success) of y*/
  /* End of cleaning variable y */
  } /*if (f2py_success) of x*/
  /* End of cleaning variable x */
  if((PyObject *)capi_ext_tmp!=ext_capi) {
    Py_XDECREF(capi_ext_tmp); }
  }  /*if (capi_ext_tmp == NULL) ... else of ext*/
  /* End of cleaning variable ext */
  } /*if (f2py_success) of iext*/
  /* End of cleaning variable iext */
  if((PyObject *)capi_gh_tmp!=gh_capi) {
    Py_XDECREF(capi_gh_tmp); }
  }  /*if (capi_gh_tmp == NULL) ... else of gh*/
  /* End of cleaning variable gh */
  } /*if (f2py_success) of nmax*/
  /* End of cleaning variable nmax */
  } /*if (f2py_success) of b2*/
  /* End of cleaning variable b2 */
  } /*if (f2py_success) of a2*/
  /* End of cleaning variable a2 */
  } /*if (f2py_success) of erad*/
  /* End of cleaning variable erad */
  } /*if (f2py_success) of elev*/
  /* End of cleaning variable elev */
  } /*if (f2py_success) of flon*/
  /* End of cleaning variable flon */
  } /*if (f2py_success) of flat*/
  /* End of cleaning variable flat */
  } /*if (f2py_success) of igdgc*/
  /* End of cleaning variable igdgc */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of shval3 *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"mkfact",-1,{{-1}},0,(char *)F_FUNC(mkfact,MKFACT),(f2py_init_func)f2py_rout_mkfact_short_2020_2_mkfact,doc_f2py_rout_mkfact_short_2020_2_mkfact},
  {"geobfield",-1,{{-1}},0,(char *)F_FUNC(geobfield,GEOBFIELD),(f2py_init_func)f2py_rout_mkfact_short_2020_2_geobfield,doc_f2py_rout_mkfact_short_2020_2_geobfield},
  {"convrt",-1,{{-1}},0,(char *)F_FUNC(convrt,CONVRT),(f2py_init_func)f2py_rout_mkfact_short_2020_2_convrt,doc_f2py_rout_mkfact_short_2020_2_convrt},
  {"getshc2",-1,{{-1}},0,(char *)F_FUNC(getshc2,GETSHC2),(f2py_init_func)f2py_rout_mkfact_short_2020_2_getshc2,doc_f2py_rout_mkfact_short_2020_2_getshc2},
  {"interpshc",-1,{{-1}},0,(char *)F_FUNC(interpshc,INTERPSHC),(f2py_init_func)f2py_rout_mkfact_short_2020_2_interpshc,doc_f2py_rout_mkfact_short_2020_2_interpshc},
  {"extrapshc",-1,{{-1}},0,(char *)F_FUNC(extrapshc,EXTRAPSHC),(f2py_init_func)f2py_rout_mkfact_short_2020_2_extrapshc,doc_f2py_rout_mkfact_short_2020_2_extrapshc},
  {"shval3",-1,{{-1}},0,(char *)F_FUNC(shval3,SHVAL3),(f2py_init_func)f2py_rout_mkfact_short_2020_2_shval3,doc_f2py_rout_mkfact_short_2020_2_shval3},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "mkfact_short_2020_2",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};

PyMODINIT_FUNC PyInit_mkfact_short_2020_2(void) {
  int i;
  PyObject *m,*d, *s, *tmp;
  m = mkfact_short_2020_2_module = PyModule_Create(&moduledef);
  Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module mkfact_short_2020_2 (failed to import numpy)"); return m;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString(
    "This module 'mkfact_short_2020_2' is auto-generated with f2py (version:2).\nFunctions:\n"
"  mkfact(tm,h,bfm,thb,bki,nhts=len(h))\n"
"  geobfield(tm,r,theta,phi,br,bt,bp,b)\n"
"  convrt(i,gdlat,gdalt,gclat,rkm)\n"
"  getshc2(iu,fspec,nmax,erad,gh,ier)\n"
"  interpshc(date,dte1,nmax1,gh1,dte2,nmax2,gh2,nmax,gh)\n"
"  extrapshc(date,dte1,nmax1,gh1,nmax2,gh2,nmax,gh)\n"
"  shval3(igdgc,flat,flon,elev,erad,a2,b2,nmax,gh,iext,ext,x,y,z)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  Py_DECREF(s);
  mkfact_short_2020_2_error = PyErr_NewException ("mkfact_short_2020_2.error", NULL, NULL);
  /*
   * Store the error object inside the dict, so that it could get deallocated.
   * (in practice, this is a module, so it likely will not and cannot.)
   */
  PyDict_SetItemString(d, "_mkfact_short_2020_2_error", mkfact_short_2020_2_error);
  Py_DECREF(mkfact_short_2020_2_error);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }







/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"mkfact_short_2020_2");
#endif
  return m;
}
#ifdef __cplusplus
}
#endif
